runtime: nodejs16

env_variables:
  GOOGLE_CLOUD_PROJECT: 'supersat-406120'
  GCLOUD_STORAGE_BUCKET: 'supersat-406120.appspot.com'


handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /static
    static_dir: public/assets

  - url: /.*
    script: auto
